# Generated by Django 4.0.2 on 2022-03-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uporabnik',
            name='otp_auth',
            field=models.BooleanField(default=True, verbose_name='Zahtevana OTP avtentikacija'),
        ),
    ]
