# Generated by Django 4.0.2 on 2022-03-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_uporabnik_otp_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgodba',
            name='prioriteta',
            field=models.IntegerField(choices=[(3, 'Could have'), (2, 'Should have'), (1, 'Must have'), (-1, "Won't have this time")], verbose_name='Vloga pri projektu'),
        ),
    ]
