# Generated by Django 4.0.2 on 2022-04-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0002_zgodba_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='koncni_cas',
            field=models.DateField(verbose_name='Končni čas sprinta'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='zacetni_cas',
            field=models.DateField(verbose_name='Začetni čas sprinta'),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
