# Generated by Django 4.0.2 on 2022-04-12 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_zgodba_prioriteta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projekt',
            name='opis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='uporabnik',
            name='previous_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prejšnja prijava'),
        ),
        migrations.AddField(
            model_name='zgodba',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.sprint', verbose_name='Sprint'),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Ime'),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Priimek'),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Uporabniško ime'),
        ),
        migrations.AlterField(
            model_name='zgodba',
            name='prioriteta',
            field=models.IntegerField(choices=[(3, 'Could have'), (2, 'Should have'), (1, 'Must have'), (-1, "Won't have this time")], verbose_name='Prioriteta'),
        ),
        migrations.RemoveField(
            model_name='clan',
            name='vloga',
        ),
        migrations.CreateModel(
            name='ScrumMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.projekt', verbose_name='Projekt')),
                ('uporabnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uporabnik')),
            ],
            options={
                'verbose_name': 'Scrum Master',
                'verbose_name_plural': 'Scrum Master',
                'unique_together': {('projekt', 'uporabnik')},
            },
        ),
        migrations.CreateModel(
            name='ProjectOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.projekt', verbose_name='Projekt')),
                ('uporabnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uporabnik')),
            ],
            options={
                'verbose_name': 'Project Owner',
                'verbose_name_plural': 'Project Owner',
                'unique_together': {('projekt', 'uporabnik')},
            },
        ),
    ]
