# Generated by Django 4.0.2 on 2022-04-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_clan_unique_together_projekt_opis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naloga',
            name='ime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ime naloge'),
        ),
        migrations.AlterField(
            model_name='naloga',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Nedodeljena'), (0, 'Dodeljena'), (1, 'Aktivna'), (2, 'Zaključena')], verbose_name='Status naloge'),
        ),
    ]
