# Generated by Django 4.0.2 on 2022-04-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_naloga_ime_alter_naloga_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='naloga',
            unique_together=set(),
        ),
    ]
