# Generated by Django 4.0.2 on 2022-04-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_naloga_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgodba',
            name='realizirana',
            field=models.BooleanField(default=False, verbose_name='Realizirana zgodba'),
        ),
    ]
